project:
  type: website
  render:
    - index.qmd
    - lessons/
  resources:
    - CNAME
    - robots.txt
  preview:
    port: 7827
    browser: false
    navigate: false
    timeout: 3600

website:
  title: CY105
  description: Computing Fundamentals
  site-url: https://cy105.bhatia.dev/
  page-footer: "© 2024 Sonny Bhatia"
  image: /images/wp_crest_new_only.png
  favicon: /images/favicon_0.ico
  page-navigation: true
  open-graph: true
  search: true
  navbar:
    logo: /images/wp_crest_new_only.png
    foreground: black
    background: "#d3bc8d"

format:
  html:
    toc: true
    toc-expand: 1
    code-fold: true
    smooth-scroll: true
    page-layout: full
    fig-align: center
    theme:
      light:
        - sandstone
      dark:
        - darkly
    mermaid:
      theme: neutral
    grid:
      body-width: 1800px
  revealjs:
    author: CPT Sonny Bhatia
    logo: /images/wp_crest_new_only.png
    center: true
    date-format: full
    transition: concave
    mouse-wheel: true
    default-timing: 60
    preview-links: false
    link-external-newwindow: true
    link-external-icon: true
    pause: false
    code-block-height: 800px
    # code-copy: false
    code-annotations: select
    tbl-cap-location: bottom
    slide-number: true
    pdf-separate-fragments: false
    theme: serif
    css: '/slides.css'
    mermaid:
      theme: default
    mermaid-format: png
    width: 1600
    height: 900
    chalkboard: false
    multiplex: true
