---
title: "Computing Fundamentals"
lightbox: true
format: html
listing:
    id: lessons
    type: grid
    sort: filename asc
    grid-columns: 5
    page-size: 50
    contents:
        - lessons/
---

- [CPT Sonny Bhatia](https://bhatia.dev/)
- Office: Thayer Hall 106
- Class Hours: A1, C1, A2, B2 (Fall 2024)

This course introduces the fundamentals of computing and cyberspace and blends theoretical knowledge with the practical application of computer hardware, software (programming), and cyberspace. Emphasis is placed on developing critical thinking skills and understanding the legal, ethical, and professional considerations as well as the challenges, opportunities, and attributes of the cyber domain.

## How to get better at CY105?

1. Complete [zyBook](https://learn.zybooks.com/zybook/WESTPOINTCY105Fall2024) required readings.
1. Attempt [zyBook](https://learn.zybooks.com/zybook/WESTPOINTCY105Fall2024) practice ICEs going back to the chapter that you do not fully grasp.
1. Seek assistance. Email me or book additional instruction.

Your success in any course depends on how many problems you successfully solve without assistance.

## Additional Instruction

- Use [Outlook Bookings](https://outlook.office.com/bookwithme/user/eb7d00eba18d43f0a98c54dee80af31d@westpoint.edu/meetingtype/jltYy6M1Zk-gtINzpqM9Zw2) to schedule a time.
    - Please make the bookings in **Eastern Time**. If your computer or Outlook calendar shows a different time, pay extra attention.
    - Automatic booking is limited to 1100-1600. If you can see times outside that window, those are not in Eastern time.
- Come prepared with **specific questions**!

::: {.callout-note}
If Outlook booking times do not work, please email me. B1 and C2 hours (Fall 2024) are generally open. I can also meet outside of listed hours if needed. Reach out.
:::

::: {.callout-warning}
Once you setup a meeting, it becomes your __assigned place of duty__. If you cannot make it, please notify me ahead of time. Not showing up to a scheduled meeting and failing to notify me ahead of time will typically result in a negative COR.
:::

## PDR or DAC counseling

- [Book a meeting](https://outlook.office.com/bookwithme/user/eb7d00eba18d43f0a98c54dee80af31d@westpoint.edu) - select the appropriate meeting type
    - This is not Additional Instruction. To setup AI, scroll up.

## Lessons

::: {#lessons}
:::

## Course Objectives

1. Examine _legal, ethical, professional, and security issues_ associated with the cyber domain.
1. Function as an _ethical, secure, and competent user_ in West Point’s immersive technology and cyber environment.
1. Apply _sequential logic_, _control flow statements_, and _code libraries_ using a modern programming language, algorithmic thinking, and a problem-solving process.
1. Describe _how data flows from data sources_ across air, land, sea, and cyberspace to form a network of information that is constantly being tracked and exploited by allies, adversaries, and third parties.
1. Describe and explore the _opportunities and challenges presented by artificial intelligence_ in the modern world.

## Course Material

- [Canvas](https://westpoint.instructure.com/courses/7068)
- [zyBook](https://learn.zybooks.com/zybook/WESTPOINTCY105Fall2024/)
- [Programming References on Canvas](https://westpoint.instructure.com/courses/7068/pages/programming-references)
- [Robotics Lab](https://usma-eecs.github.io/CY105_Lab/index.html)
    - [CircuitPython Code Editor](https://code.circuitpython.org/) - IDE to work with Circuit Playground Bluefruit
    - [Mu Editor](https://codewith.mu/) - less desirable IDE for Circuit Playground Bluefruit
    - [Circuit Playground Bluefruit](https://www.adafruit.com/product/764) - try student discount code: `GitHubEdu`
    - [Circuit Playground Bluefruit](https://www.adafruit.com/product/4333) - no discount but easier to order

## Documentation and Tutorials

- [DevDocs.io](https://devdocs.io/python~3.12/)
- [Python Notes for Professionals](https://goalkicker.com/PythonBook/)
- [Official Python Documentation](https://docs.python.org/)
- [Programming References on Canvas](https://westpoint.instructure.com/courses/7068/pages/programming-references)
- [How to Python in VS Code](https://py-vscode.readthedocs.io/)
- [Hour of Python](https://hourofpython.com/)
- [Khan Academy: Intro to Python Fundamentals](https://www.khanacademy.org/computing/intro-to-python-fundamentals)

## Developer Tools

- [Marimo](https://marimo.app/) reactive notebook for Python
- [diff Check](https://diffcheck.io/) - compare text side-by-side; great for comparing expected and actual output
- [Pyodide](https://pyodide.org/en/stable/console.html) - in-browser REPL
- [Python Tutor](https://pythontutor.com/python-compiler.html) - step through code execution, line-by-line
- [Black Code Formatter](https://black.vercel.app/) - format Python code following [PEP 8 Style Guide](https://peps.python.org/pep-0008/)
    - zyLab does this too if you right click and select "Format Document"
- [Thonny](https://thonny.org/) - Python development environment for beginners
- [Visual Studio Code](https://code.visualstudio.com/) - development environment for grown-ups
- [Notepad++](https://notepad-plus-plus.org/) - lightweight text editor

## AI Summative Project

### Ideas

- [Make It Yourself](https://makeityourself.org/) - A Beautifully Illustrated Guide to Making
- [Hackaday](https://hackaday.com/)
- [Hacker News: Show](https://news.ycombinator.com/show)
- [Example Projects [Canvas]](https://westpoint.instructure.com/courses/7068/files/1911864/download)
- [Text-based adventure game [zybook]](https://learn.zybooks.com/zybook/WESTPOINTCY105Fall2024/chapter/17/section/1)
- [zork-py](https://github.com/iamjawa/zork-py) library for Python
- [Kaggle Data Science Notebook](https://www.kaggle.com/code/ldfreeman3/a-data-science-framework-to-achieve-99-accuracy#Step-4:-Perform-Exploratory-Analysis-with-Statistics)
- Circuit Playground Bluefruit: Puzzle Box, Escape Room, etc.
    - [Fruit Piano](https://www.youtube.com/embed/UibfAZb1Xwo)

### Tools and Resources

- [tldraw makereal](https://makereal.tldraw.com/) - bring your application sketches to life! - [watch demo](https://www.youtube.com/embed/Ov2N2fd6Xm4)
- Develop applications that use AI at runtime-
    - [OpenAI API](https://platform.openai.com/) - message them for API credits as a student researcher
    - [Anthropic API](https://console.anthropic.com/) - free limited API access
    - [Streamlit](https://streamlit.io/) - hosting platform to turn data scripts into shareable web apps using Python
- [Deepnote](https://deepnote.com/) - interactive web applications in Python
- [Marimo](https://marimo.io/) - interactive web applications in Python
- [GitHub pages](https://pages.github.com/) - host your websites and JavaScript applications for free
- [Visual Studio Code](https://code.visualstudio.com/) - development environment for grown-ups
    - [Github CoPilot](https://docs.github.com/en/copilot/managing-copilot/managing-copilot-as-an-individual-subscriber/managing-your-copilot-subscription/getting-free-access-to-copilot-as-a-student-teacher-or-maintainer) - AI-powered code completion on steroids; free for students
    - [Serial Monitor extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-serial-monitor) - interface with your microcontroller from within VSCode
- [Using Bluetooth (BLE) with Circuit Playground Bluefruit](https://github.com/adafruit/Adafruit_CircuitPython_BLE_Radio)

## Awesome Links and Resources

### Computing and Technology

- [Hackaday](https://hackaday.com/)
- [Hide and Seek!](https://www.youtube.com/embed/Lu56xVlZ40M)
- [Can ChatGPT be wrong?](https://chatgpt.com/share/a329b032-7e1d-4568-be40-9227de866a8b)
- [What is Python](https://www.youtube.com/embed/x7X9w_GIm1s)
- [arrr](https://arrr.readthedocs.io/) - Pirate module for Python
- [Where really is the Internet?](https://www.youtube.com/embed/Ve810FHZ1CQ)
- [Seating chart generator](https://gist.github.com/aadityabhatia/86077fea4ccd353bfb017df733a70d19)
- [Vortex Cannon vs Drone](https://www.youtube.com/embed/SrGENEXocJU)

### Cyber, Security, and Privacy

#### Learning Resources
- [Building a home lab](https://aj-labz.gitbook.io/aj-labz)
- [USASOC Smart Cards](https://www.soc.mil/IdM/publications/IdMpubs.html)
- [Terms of Service; Didn't Read](https://tosdr.org/)

####  Tracker, Ad-blockers, and Malware Protection
- [Cloudflare for Families](https://blog.cloudflare.com/introducing-1-1-1-1-for-families/) - DNS-based tracker and adult content blocker
- [Pi-hole](https://pi-hole.net/) - network-wide DNS-based ad blocker
- [pfSense](https://www.pfsense.org/) - open-source firewall
- [NextDNS](https://nextdns.io/) - DNS-based tracker blocker

####  Self-hosted services, tools, networks
- [Tailscale](https://tailscale.com/) - mesh networking (personal VPN) for your devices
- [Syncthing](https://syncthing.net/) - file synchronization across devices
- [Nextcloud](https://nextcloud.com/) - self-hosted cloud storage, calendar, contacts, [RSS feed reader](https://en.wikipedia.org/wiki/RSS)
- [Gitea](https://gitea.io/) - self-hosted Git service, replacement for GitHub
- [Bitwarden](https://bitwarden.com/) - self-hosted password manager
- [Jitsi](https://jitsi.org/) - self-hosted video conferencing
- [Mattermost](https://mattermost.com/) - self-hosted Slack alternative

#### Messaging, Email, Communication
- [Signal Messenger](https://signal.org/) - non-profit, encrypted messaging, voice, and video calls
- [ProtonMail](https://protonmail.com/) - encrypted email
- [Element](https://element.io/) - encrypted chat, video, and voice calls based on [Matrix](https://matrix.org/) protocol; can run your own server
- [PGP Encryption](https://www.privacytools.io/encryption-tools/pgp/gpg/)

#### News, Articles, Documentaries
- [Flipper Zero](https://www.youtube.com/embed/nLIp4wd0oXs)
    - [Meanwhile, in Canada...](https://arstechnica.com/security/2024/02/canada-vows-to-ban-flipper-zero-device-in-crackdown-on-car-theft/)
- [Inside the "3 Billion People" National Public Data Breach](https://www.troyhunt.com/inside-the-3-billion-people-national-public-data-breach/)
- [The Global Surveillance Free-for-All in Mobile Ad Data (2024)](https://krebsonsecurity.com/2024/10/the-global-surveillance-free-for-all-in-mobile-ad-data/)
- [Why digital privacy matters](https://www.privacyguides.org/en/basics/why-privacy-matters/)
- [The Social Dilemma (2020)](https://www.netflix.com/title/81254224) - documentary on social media
- [The Great Hack (2019)](https://www.netflix.com/title/80117542) - documentary on Cambridge Analytica scandal

#### What can you do?
- [haveibeenpwned.com](https://haveibeenpwned.com/) - subscribe to breach notifications
- [Mozilla Monitor](https://monitor.mozilla.org/) - find and fix data exposures
- [Firefox](https://www.mozilla.org/en-US/firefox/) - privacy-focused browser
- [DuckDuckGo](https://duckduckgo.com/privacy) - privacy-focused search engine
- [Cover Your Tracks](https://coveryourtracks.eff.org/) - browser fingerprinting test
- [NextDNS](https://nextdns.io/) - DNS-based tracker blocker
    - or self-host [Pi-hole](https://pi-hole.net/)
- [Privacy Guides](https://www.privacyguides.org/) - privacy-focused tools and recommendations
    - [PrivacyTools](https://www.privacytools.io/)
- [Consumer Reports: Privacy and Security](https://www.consumerreports.org/digital-security-privacy/)
- [Surveillance Self-Defense](https://ssd.eff.org/)
- [Data Removal Guide: inteltechniques.com](https://inteltechniques.com/workbook.html)

### Learning and Productivity
- [PB&J Sandwich](https://www.youtube.com/watch?v=FN2RM-CHkuI)
- [YouTube: Bloom’s Taxonomy: Structuring The Learning Journey](https://www.youtube.com/embed/ayefSTAnCR8)
    - Ref: [Armstrong, P. (2010). Bloom’s Taxonomy. Vanderbilt University Center for Teaching.](https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/)
- [Pareto Principle [The 80/20 Rule Explained]](https://www.youtube.com/embed/lsGwqk_agcQ)
- [Growth Mindset](https://www.youtube.com/embed/KUWn_TJTrnU)
- Why take good notes?
    - [Active learning](https://www.youtube.com/embed/xxVxgQJwV7w)
    - Memory retention
    - Future reference
- How to take good notes?
    - [Logseq](https://logseq.com/) or [Obsidian](https://obsidian.md/) - journaling, linking, knowledge management
    - OneNote
    - [Zettelkasten](https://zettelkasten.de/) - integrated thinking method!
        - [Zettelkasten Explained](https://www.youtube.com/embed/GpV47rUYk8I)
- The need for sleep
    - [Your Brain On Sleep Deprivation](https://www.youtube.com/embed/lvKrDsreUgM)
    - [What would happen if you didn’t sleep?](https://www.youtube.com/embed/dqONk48l5vY)
    - [How Sleep Affects Your Brain](https://www.youtube.com/embed/IzQ2siryQrM)
- Algorithm: [The Better Boarding Method Airlines Won't Use](https://www.youtube.com/embed/oAHbLRjF0vo)
- [About, Ideas, Now](https://aboutideasnow.com/)
